version: '3'
services:
  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    container_name: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    volumes:
      - ./localstack/:/etc/localstack/init/ready.d