@startuml
class 払出 {
  - 払出ID
  - 払出種別
  - 商品コード
  - 払出日付
  - 数量
  - 備考
}

class 商品 {
  - 商品コード
  - メーカーコード
  - 商品名
  - 廃盤フラグ
}

class メーカー {
  - メーカーコード
  - メーカー名
}

払出 "0..*" -- "1" 商品
商品 "0..*" -- "1" メーカー
@enduml